RGBLIGHT_ENABLE    = no
MOUSEKEY_ENABLE    = no
RGB_MATRIX_ENABLE  = WS2812
OLED_DRIVER_ENABLE = yes
EXTRAKEY_ENABLE    = yes
NKRO_ENABLE        = no
BOOTLOADER         = atmel-dfu

EXTRAFLAGS += -flto